### ISSUE TITLE
Fetch Maven artifacts in 0.2.0 via secure URLs

### ISSUE THREAD

**Issue by vmax** [marcohu/rules_antlr#8]
Recently Maven Central started enforcing HTTPS when downloading artifacts ([ref](https://support.sonatype.com/hc/en-us/articles/360041287334))

We've fixed the URLs as per their suggestion in our fork: https://github.com/graknlabs/rules_antlr/tree/0.2.1

@marcohu would it be possible for you to release `0.2.1` which contains updated URLs?  Unfortunately, upgrading to 0.4.0 for us is not an option because we're using Java 8 and it contains code that is only compatible with Java 11 (such as `String::isBlank`)

**Comment by marcohu** [comment]
The real issue is the unwanted Java 11 dependency. It has been fixed in the dev branch. I will cut a new release when support for 4.8 and 4.7.3 has been added, but I won't touch the old code.

Thanks for bringing the issue to my attention.
